### ISSUE TITLE
The output for the kperf service clean command is incorrect

### ISSUE THREAD

**Issue by beemarie** [knative-sandbox/kperf#12]
For this command, the namespace should be test1, with any service named ktest*
The actual behavior appears correct in that my services were cleaned up.
```
kperf service clean --nsPrefix test --nsRange 1,1 --svcPrefix ktest
Delete ksvc test1 in namespace ktest-0
Delete ksvc test1 in namespace ktest-1
Delete ksvc test1 in namespace ktest-11
Delete ksvc test1 in namespace ktest-13
Delete ksvc test1 in namespace ktest-16
Delete ksvc test1 in namespace ktest-12
Delete ksvc test1 in namespace ktest-17
```

**Comment by zhanggbj** [comment]
@beemarie Thanks for reporting the issue. We'll take a look. CC @qibobo^^^^

**Comment by zhanggbj** [comment]
/assign @qibobo 
Talked with Yang offline, he's checking on this.

**Comment by qibobo** [comment]
@beemarie 
Thank you for reporting it. It will be fixed in the next PR.

**Comment by zhanggbj** [comment]
@beemarie the PR is merged, would you please try again and close it if it is fixed? Thanks!

**Comment by zhanggbj** [comment]
Close it as issue has no activities.
Please feel free to reopen it if the issue still exists.

/CC @beemarie
