### ISSUE TITLE
Unable to run kperf with OpenShift 

### ISSUE THREAD

**Issue by aslom** [knative-sandbox/kperf#13]
```
./kperf service generate -n 30 -b 10 -c 5 -i 15 --nsPrefix test --nsRange 1,3 --svcPrefix ktest --maxScale 1 --minScale 1
Error: namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope
Usage:
  kperf service generate [flags]

Flags:
  -b, --batch int          Number of ksvc each time to be created
  -c, --concurrency int    Number of multiple ksvcs to make at a time (default 10)
  -h, --help               help for generate
  -i, --interval int       Interval for each batch generation
      --maxScale int       For autoscaling.knative.dev/minScale
      --minScale int       For autoscaling.knative.dev/minScale
      --ns string          Namespace name. The ksvc will be created in the namespace
  -p, --nsPrefix string    Namespace prefix. The ksvc will be created in the namespaces with the prefix
      --nsRange string
  -n, --number int         Total number of ksvc to be created
      --svcPrefix string   ksvc name prefix. The ksvcs will be svcPrefix1,svcPrefix2,svcPrefix3...... (default "testksvc")
      --timeout duration   duration to wait for previous ksvc to be ready (default 10m0s)
      --wait               whether wait the previous ksvc to be ready

2020/11/17 09:34:07 failed to execute kperf command: namespaces is forbidden: User "system:anonymous" cannot list resource "namespaces" in API group "" at the cluster scope
```

**Comment by aslom** [comment]
Add some way for users ot create namespaces?

Or some safe way to grant limited permissions to kperf?

**Comment by zhanggbj** [comment]
@aslom Thanks for opening this!
Yes, we'll add namespaces creation soon tracking here https://github.com/knative-sandbox/kperf/issues/7 and will take a look at the permission issue above. CC @gyohuangxin as you have more experience with OpenShift.

**Comment by gyohuangxin** [comment]
@zhanggbj Yes, I will try it on my OpenShift soon.
@aslom  Cloud you pls provide your OpenShift info, such as version, platform?

**Comment by gyohuangxin** [comment]
@aslom  I thinks it's not an OpenShift issue. According to the kperf design, kperf will create namespaces, so at this stage, you must run kperf as user who can create namespaces.

**Comment by aslom** [comment]
It is OCP 4.5 

@gyohuangxin how do i setup user that can create namespaces?

**Comment by gyohuangxin** [comment]
@aslom 

According to [Openshift Users doc](https://docs.openshift.com/container-platform/4.5/authentication/understanding-authentication.html#rbac-users_understanding-authentication), `User "system:anonymous"` is an user with no authentication, once authenticated, policy determines what the user is authorized to do. So maybe you should  contact your OpenShift administrator to authenticate.

**Comment by aslom** [comment]
@gyohuangxin I am administrator of that cluster - maybe kperf is not using admin permissions by default? how do i check what user is kperf using?
