### ISSUE TITLE
As a Kperf developer, I want to add --verbose flag for debugging purpose 

### ISSUE THREAD

**Issue by zhanggbj** [knative-sandbox/kperf#17]
To expose more debugging info for end-users, add --verbose flag in kperf.

**Comment by zhanggbj** [comment]
Hi Owen @zhi-gang-sun , are you still working on this? Thanks!

As we want to use --verbose to provide more debug info the end user, just would like to know if you still have bandwidth

**Comment by zhi-gang-sun** [comment]
@zhanggbj nope, and may not have bandwidth in coming weeks so feel free to take it.

**Comment by gyohuangxin** [comment]
@zhanggbj @zhi-gang-sun Thanks! I will work on this

**Comment by zhanggbj** [comment]
Thanks @zhi-gang-sun and @gyohuangxin !

/unassign @zhi-gang-sun 
/assign @gyohuangxin
