### ISSUE TITLE
Scale a service from 0 to n and measure the latency

### ISSUE THREAD

**Issue by daisy-ycguo** [knative-sandbox/kperf#223]
### Use case
As a knative user, I want to measure the latencies when scaling a service from 0 to n. I can use a load test tool to send requests and measure the data when scaling from zero to n.

### Command
kperf scale --namespace ktest --concurrency 5 --duration 30 --svc-prefix ktest --range 0,9 --target 100 --verbose --output /tmp

### Behaviors
This command will scale the service from zero to 100 and get the durations when reaching 100 running pods. A load test tool is used to generate requests till the replicas reaches the target. The the parameters of http load generator will be set manually or automatically.

### Measure
Below data will be measured or collected.

- Over all
  - Latency when number of running pod is reaching the target
  - Latency when Deployment.Spec.ReadyReplicas is reaching the target
 
- For each pod/instance/replica
  - Duration for every running pod
  - Duration for every container, user containers, queue-proxy container getting ready
  - Duration for every route getting ready

**Comment by maximilien** [comment]
@psschwei tagging you here in case you have suggestion to this feature request Daisy is proposing. WDYT?

**Comment by psschwei** [comment]
A scale feature was added in #133 , though I believe right now it only measures service/deployment latency. I'm +1 on expanding the metrics collected.

**Comment by daisy-ycguo** [comment]
> A scale feature was added in #133 , though I believe right now it only measures service/deployment latency. I'm +1 on expanding the metrics collected.

Thank you for the feedback Paul.
I know there is a scale command, but it's only use a http request to trigger an instance and measure only 0 ->1.  0 -> 1 is only a measure of 1 instance without any pressure.
My proposal is to use a load test tool and measure 0 -> n. I think it's useful to understand the behaviour of Knative under some kind of load pressure.

**Comment by psschwei** [comment]
Thanks for the clarification. Totally agree that "scale to N" under load would be good to measure.

**Comment by chzhyang** [comment]
I will take this issue. 
./assign chzhyang
