### ISSUE TITLE
As a Kperf developer, I want to show basic information about Knative

### ISSUE THREAD

**Issue by gyohuangxin** [knative-sandbox/kperf#35]
We need to get some basic info about Knative(version, release ....) and put the results in a JSON file as https://github.com/knative-sandbox/kperf/issues/34 mentioned.

/assign @gyohuangxin

**Comment by gyohuangxin** [comment]
Info:

- [ ] Knative(serving and eventing) version and release no
- [ ] Start and end time
- [ ] Network layer info

**Comment by zhanggbj** [comment]
done
