### ISSUE TITLE
Align repository with other Knative repos

### ISSUE THREAD

**Issue by markusthoemmes** [knative-sandbox/kperf#39]
Heya :wave: 

I've had a look at `kperf` today and noted that it's not behaving like other Knative repositories does and wondered if we should make it do that.

Notable differences:
1. No `./hack/update-deps.sh`, so no LICENSE handling etc.
2. No `vendor` so there is a manual copy of test infra in here.

I'd be down to help fix those if wanted.

**Comment by zhanggbj** [comment]
Hi @markusthoemmes ,

Thank you for taking care of them! 
(As you may know, Kperf repo was created at the end of last year and is under development now.)

**Comment by markusthoemmes** [comment]
@zhanggbj sure, I hope this work wouldn't impede any ongoing development work :). I just want to make sure we're adhering to how other repos work so people can contribute more easily.

**Comment by zhanggbj** [comment]
@markusthoemmes Sound great! And absolutely this helps a lot and won't impact any dev work. This repo still got a lot of TODOs and feel free to open any issues:-)
