### ISSUE TITLE
As a Kperf developer, I want to fill up Unit Test

### ISSUE THREAD

**Issue by zhanggbj** [knative-sandbox/kperf#5]
Refer to https://github.com/knative-sandbox/kn-plugin-admin/tree/master/pkg/command/domain to setup UT frame work.

**Comment by zhanggbj** [comment]
/assign @gyohuangxin 
Per offline discussion, Xin would like to take this.

**Comment by zhanggbj** [comment]
@chizhg @evankanderson Xin(@gyohuangxin ) is from our team and currently focusing on **kperf** development, would you please help to add him to knative-sandbox members, thanks in advance!

**Comment by chizhg** [comment]
> @chizhg @evankanderson Xin(@gyohuangxin ) is from our team and currently focusing on **kperf** development, would you please help to add him in knative-sandbox org, thanks in advance!

Adding a new member to the knative and knative-sandbox is pretty much a self-service, you could just submit a PR to update https://github.com/knative/community/tree/master/peribolos to add their GitHub usernames, and after the PR is merged, they will receive an invitation to join the org(s).

**Comment by zhanggbj** [comment]
@chizhg Thanks a lot for the info! Will raise a PR later:-)

**Comment by zhanggbj** [comment]
Merged!
